package wg.media.screen.fm.model.commandscreen;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("app_version", "auto_id", AppVersion.class);
		arp.addMapping("application_setting", "id", ApplicationSetting.class);
		arp.addMapping("archive_file", "file_id", ArchiveFile.class);
		arp.addMapping("business_file_relation", "id", BusinessFileRelation.class);
		arp.addMapping("compilatio_spread", "id", CompilatioSpread.class);
		arp.addMapping("const_dictionary", "id", ConstDictionary.class);
		arp.addMapping("draft", "d_id", Draft.class);
		arp.addMapping("draft_relation", "d_id", DraftRelation.class);
		arp.addMapping("im_feedback", "id", ImFeedback.class);
		arp.addMapping("interview_plan", "id", InterviewPlan.class);
		arp.addMapping("manage_client_video", "auto_id", ManageClientVideo.class);
		arp.addMapping("manage_media_matrix", "auto_id", ManageMediaMatrix.class);
		arp.addMapping("meeting", "m_id", Meeting.class);
		arp.addMapping("meeting_member", "id", MeetingMember.class);
		arp.addMapping("notice", "n_id", Notice.class);
		arp.addMapping("notice_comments", "id", NoticeComments.class);
		arp.addMapping("notice_comments_reply", "id", NoticeCommentsReply.class);
		arp.addMapping("notice_data", "n_id", NoticeData.class);
		arp.addMapping("notice_log", "n_id", NoticeLog.class);
		arp.addMapping("notice_member", "id", NoticeMember.class);
		arp.addMapping("notification_information", "id", NotificationInformation.class);
		arp.addMapping("open_config", "auto_id", OpenConfig.class);
		arp.addMapping("open_invoke_info", "auto_id", OpenInvokeInfo.class);
		arp.addMapping("open_layout", "auto_id", OpenLayout.class);
		arp.addMapping("open_module", "auto_id", OpenModule.class);
		arp.addMapping("open_ref_user_invoke", "auto_id", OpenRefUserInvoke.class);
		arp.addMapping("planning_scheme", "p_id", PlanningScheme.class);
		arp.addMapping("products_analysis", "id", ProductsAnalysis.class);
		arp.addMapping("red_dot", "id", RedDot.class);
		arp.addMapping("scene", "s_id", Scene.class);
		arp.addMapping("scheme_relation", "s_id", SchemeRelation.class);
		arp.addMapping("source", "s_id", Source.class);
		arp.addMapping("task", "t_id", Task.class);
		arp.addMapping("task_log", "t_id", TaskLog.class);
		arp.addMapping("task_member", "id", TaskMember.class);
		arp.addMapping("task_process_progress", "id", TaskProcessProgress.class);
		arp.addMapping("topic", "t_id", Topic.class);
		arp.addMapping("topic_member", "id", TopicMember.class);
		arp.addMapping("umeng", "id", Umeng.class);
	}
}

