package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseApplicationSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ApplicationSetting extends BaseApplicationSetting<ApplicationSetting> {
	public static final ApplicationSetting dao = new ApplicationSetting().dao();
}
