package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseAppVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppVersion extends BaseAppVersion<AppVersion> {
	public static final AppVersion dao = new AppVersion().dao();
}
