package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseArchiveFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArchiveFile extends BaseArchiveFile<ArchiveFile> {
	public static final ArchiveFile dao = new ArchiveFile().dao();
}
