package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseBusinessFileRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusinessFileRelation extends BaseBusinessFileRelation<BusinessFileRelation> {
	public static final BusinessFileRelation dao = new BusinessFileRelation().dao();
}
