package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseChat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Chat extends BaseChat<Chat> {
	public static final Chat dao = new Chat().dao();
}
