package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseChatComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChatComment extends BaseChatComment<ChatComment> {
	public static final ChatComment dao = new ChatComment().dao();
}
