package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseCompilatioSpread;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CompilatioSpread extends BaseCompilatioSpread<CompilatioSpread> {
	public static final CompilatioSpread dao = new CompilatioSpread().dao();
}
