package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseConstDictionary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ConstDictionary extends BaseConstDictionary<ConstDictionary> {
	public static final ConstDictionary dao = new ConstDictionary().dao();
}
