package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseDraft;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Draft extends BaseDraft<Draft> {
	public static final Draft dao = new Draft().dao();
}
