package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseDraftRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DraftRelation extends BaseDraftRelation<DraftRelation> {
	public static final DraftRelation dao = new DraftRelation().dao();
}
