package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseImFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImFeedback extends BaseImFeedback<ImFeedback> {
	public static final ImFeedback dao = new ImFeedback().dao();
}
