package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseInterviewPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InterviewPlan extends BaseInterviewPlan<InterviewPlan> {
	public static final InterviewPlan dao = new InterviewPlan().dao();
}
