package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseManageClientVideo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageClientVideo extends BaseManageClientVideo<ManageClientVideo> {
	public static final ManageClientVideo dao = new ManageClientVideo().dao();
}
