package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseManageMediaMatrix;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageMediaMatrix extends BaseManageMediaMatrix<ManageMediaMatrix> {
	public static final ManageMediaMatrix dao = new ManageMediaMatrix().dao();
}
