package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseMediaDraftnum;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MediaDraftnum extends BaseMediaDraftnum<MediaDraftnum> {
	public static final MediaDraftnum dao = new MediaDraftnum().dao();
}
