package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseMeetingMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MeetingMember extends BaseMeetingMember<MeetingMember> {
	public static final MeetingMember dao = new MeetingMember().dao();
}
