package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseMeeting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Meeting extends BaseMeeting<Meeting> {
	public static final Meeting dao = new Meeting().dao();
}
