package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseNotificationInformation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NotificationInformation extends BaseNotificationInformation<NotificationInformation> {
	public static final NotificationInformation dao = new NotificationInformation().dao();
}
