package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseNoticeData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NoticeData extends BaseNoticeData<NoticeData> {
	public static final NoticeData dao = new NoticeData().dao();
}
