package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseNoticeLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NoticeLog extends BaseNoticeLog<NoticeLog> {
	public static final NoticeLog dao = new NoticeLog().dao();
}
