package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseNoticeComments;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NoticeComments extends BaseNoticeComments<NoticeComments> {
	public static final NoticeComments dao = new NoticeComments().dao();
}
