package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseNoticeMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NoticeMember extends BaseNoticeMember<NoticeMember> {
	public static final NoticeMember dao = new NoticeMember().dao();
}
