package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseNoticeCommentsReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NoticeCommentsReply extends BaseNoticeCommentsReply<NoticeCommentsReply> {
	public static final NoticeCommentsReply dao = new NoticeCommentsReply().dao();
}
