package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseOpenRefUserInvoke;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OpenRefUserInvoke extends BaseOpenRefUserInvoke<OpenRefUserInvoke> {
	public static final OpenRefUserInvoke dao = new OpenRefUserInvoke().dao();
}
