package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseOpenInvokeInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OpenInvokeInfo extends BaseOpenInvokeInfo<OpenInvokeInfo> {
	public static final OpenInvokeInfo dao = new OpenInvokeInfo().dao();
}
