package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseOpenLayout;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OpenLayout extends BaseOpenLayout<OpenLayout> {
	public static final OpenLayout dao = new OpenLayout().dao();
}
