package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseOpenModule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OpenModule extends BaseOpenModule<OpenModule> {
	public static final OpenModule dao = new OpenModule().dao();
}
