package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseOpenConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OpenConfig extends BaseOpenConfig<OpenConfig> {
	public static final OpenConfig dao = new OpenConfig().dao();
}
