package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BasePlanningScheme;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlanningScheme extends BasePlanningScheme<PlanningScheme> {
	public static final PlanningScheme dao = new PlanningScheme().dao();
}
