package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseProductsAnalysis;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductsAnalysis extends BaseProductsAnalysis<ProductsAnalysis> {
	public static final ProductsAnalysis dao = new ProductsAnalysis().dao();
}
