package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseRedDot;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RedDot extends BaseRedDot<RedDot> {
	public static final RedDot dao = new RedDot().dao();
}
