package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseScene;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Scene extends BaseScene<Scene> {
	public static final Scene dao = new Scene().dao();
}
