package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseSchemeRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SchemeRelation extends BaseSchemeRelation<SchemeRelation> {
	public static final SchemeRelation dao = new SchemeRelation().dao();
}
