package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseSource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Source extends BaseSource<Source> {
	public static final Source dao = new Source().dao();
}
