package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseSourceEvent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SourceEvent extends BaseSourceEvent<SourceEvent> {
	public static final SourceEvent dao = new SourceEvent().dao();
}
