package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseTaskLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskLog extends BaseTaskLog<TaskLog> {
	public static final TaskLog dao = new TaskLog().dao();
}
