package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseTaskMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskMember extends BaseTaskMember<TaskMember> {
	public static final TaskMember dao = new TaskMember().dao();
}
