package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseTaskProcessProgress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskProcessProgress extends BaseTaskProcessProgress<TaskProcessProgress> {
	public static final TaskProcessProgress dao = new TaskProcessProgress().dao();
}
