package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseTopicMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TopicMember extends BaseTopicMember<TopicMember> {
	public static final TopicMember dao = new TopicMember().dao();
}
