package wg.media.screen.fm.model.commandscreen;

import wg.media.screen.fm.model.commandscreen.base.BaseUmeng;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Umeng extends BaseUmeng<Umeng> {
	public static final Umeng dao = new Umeng().dao();
}
