package wg.media.screen.fm.model.commandscreencommon;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("audience_user_info", "id", AudienceUserInfo.class);
		arp.addMapping("history_dialogue", "id", HistoryDialogue.class);
		arp.addMapping("im_action_plan", "id", ImActionPlan.class);
		arp.addMapping("im_file_mange", "id", ImFileMange.class);
		// Composite Primary Key order: id,fingerPrint
		arp.addMapping("im_history_message", "id,fingerPrint", ImHistoryMessage.class);
		arp.addMapping("im_inform", "id", ImInform.class);
		arp.addMapping("im_offline_message", "id", ImOfflineMessage.class);
		arp.addMapping("manage_depart", "dep_id", ManageDepart.class);
		arp.addMapping("manage_group", "group_id", ManageGroup.class);
		arp.addMapping("manage_group_user_task_rel", "id", ManageGroupUserTaskRel.class);
		arp.addMapping("manage_institution", "id", ManageInstitution.class);
		arp.addMapping("manage_media", "media_id", ManageMedia.class);
		arp.addMapping("manage_perm", "id", ManagePerm.class);
		arp.addMapping("manage_role", "id", ManageRole.class);
		// Composite Primary Key order: rid,pid
		arp.addMapping("manage_role_perm_rel", "rid,pid", ManageRolePermRel.class);
		// Composite Primary Key order: rid,uid
		arp.addMapping("manage_role_user_rel", "rid,uid", ManageRoleUserRel.class);
		arp.addMapping("manage_user_info", "user_id", ManageUserInfo.class);
		arp.addMapping("manage_user_info_copy1", "user_id", ManageUserInfoCopy1.class);
		arp.addMapping("manager_user_record", "id", ManagerUserRecord.class);
		arp.addMapping("media_store_info", "id", MediaStoreInfo.class);
	}
}

