package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseAudienceUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AudienceUserInfo extends BaseAudienceUserInfo<AudienceUserInfo> {
	public static final AudienceUserInfo dao = new AudienceUserInfo().dao();
}
