package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseHistoryDialogue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HistoryDialogue extends BaseHistoryDialogue<HistoryDialogue> {
	public static final HistoryDialogue dao = new HistoryDialogue().dao();
}
