package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseImActionPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImActionPlan extends BaseImActionPlan<ImActionPlan> {
	public static final ImActionPlan dao = new ImActionPlan().dao();
}
