package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseImFileMange;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImFileMange extends BaseImFileMange<ImFileMange> {
	public static final ImFileMange dao = new ImFileMange().dao();
}
