package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseImHistoryMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImHistoryMessage extends BaseImHistoryMessage<ImHistoryMessage> {
	public static final ImHistoryMessage dao = new ImHistoryMessage().dao();
}
