package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseImInform;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImInform extends BaseImInform<ImInform> {
	public static final ImInform dao = new ImInform().dao();
}
