package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseImOfflineMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImOfflineMessage extends BaseImOfflineMessage<ImOfflineMessage> {
	public static final ImOfflineMessage dao = new ImOfflineMessage().dao();
}
