package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseManageRoleUserRel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageRoleUserRel extends BaseManageRoleUserRel<ManageRoleUserRel> {
	public static final ManageRoleUserRel dao = new ManageRoleUserRel().dao();
}
