package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseManageRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageRole extends BaseManageRole<ManageRole> {
	public static final ManageRole dao = new ManageRole().dao();
}
