package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseManageGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageGroup extends BaseManageGroup<ManageGroup> {
	public static final ManageGroup dao = new ManageGroup().dao();
}
