package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseManageRolePermRel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageRolePermRel extends BaseManageRolePermRel<ManageRolePermRel> {
	public static final ManageRolePermRel dao = new ManageRolePermRel().dao();
}
