package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseManageDepart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageDepart extends BaseManageDepart<ManageDepart> {
	public static final ManageDepart dao = new ManageDepart().dao();
}
