package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseManageUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageUserInfo extends BaseManageUserInfo<ManageUserInfo> {
	public static final ManageUserInfo dao = new ManageUserInfo().dao();
}
