package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseManagerUserRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManagerUserRecord extends BaseManagerUserRecord<ManagerUserRecord> {
	public static final ManagerUserRecord dao = new ManagerUserRecord().dao();
}
