package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseManagePerm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManagePerm extends BaseManagePerm<ManagePerm> {
	public static final ManagePerm dao = new ManagePerm().dao();
}
