package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseManageUserInfoCopy1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageUserInfoCopy1 extends BaseManageUserInfoCopy1<ManageUserInfoCopy1> {
	public static final ManageUserInfoCopy1 dao = new ManageUserInfoCopy1().dao();
}
