package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseManageGroupUserTaskRel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageGroupUserTaskRel extends BaseManageGroupUserTaskRel<ManageGroupUserTaskRel> {
	public static final ManageGroupUserTaskRel dao = new ManageGroupUserTaskRel().dao();
}
