package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseManageInstitution;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageInstitution extends BaseManageInstitution<ManageInstitution> {
	public static final ManageInstitution dao = new ManageInstitution().dao();
}
