package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseManageMedia;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManageMedia extends BaseManageMedia<ManageMedia> {
	public static final ManageMedia dao = new ManageMedia().dao();
}
