package wg.media.screen.fm.model.commandscreencommon;

import wg.media.screen.fm.model.commandscreencommon.base.BaseMediaStoreInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MediaStoreInfo extends BaseMediaStoreInfo<MediaStoreInfo> {
	public static final MediaStoreInfo dao = new MediaStoreInfo().dao();
}
