package wg.media.screen.fm.model.commandscreencommon.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMediaStoreInfo<M extends BaseMediaStoreInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setInstId(java.lang.Integer instId) {
		set("inst_id", instId);
	}

	public java.lang.Integer getInstId() {
		return get("inst_id");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setResourceUrl(java.lang.String resourceUrl) {
		set("resourceUrl", resourceUrl);
	}

	public java.lang.String getResourceUrl() {
		return get("resourceUrl");
	}

}
