package wg.media.screen.fm.model.commandscreencommon.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAudienceUserInfo<M extends BaseAudienceUserInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setMobilePhone(java.lang.String mobilePhone) {
		set("mobile_phone", mobilePhone);
	}

	public java.lang.String getMobilePhone() {
		return get("mobile_phone");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setRegip(java.lang.String regip) {
		set("regip", regip);
	}

	public java.lang.String getRegip() {
		return get("regip");
	}

	public void setInsertTime(java.util.Date insertTime) {
		set("insert_time", insertTime);
	}

	public java.util.Date getInsertTime() {
		return get("insert_time");
	}

	public void setCountryCode(java.lang.String countryCode) {
		set("country_code", countryCode);
	}

	public java.lang.String getCountryCode() {
		return get("country_code");
	}

	public void setCountry(java.lang.String country) {
		set("country", country);
	}

	public java.lang.String getCountry() {
		return get("country");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public void setLot(java.lang.Double lot) {
		set("lot", lot);
	}

	public java.lang.Double getLot() {
		return get("lot");
	}

	public void setLat(java.lang.Double lat) {
		set("lat", lat);
	}

	public java.lang.Double getLat() {
		return get("lat");
	}

	public void setYhProfession(java.lang.String yhProfession) {
		set("yh_profession", yhProfession);
	}

	public java.lang.String getYhProfession() {
		return get("yh_profession");
	}

	public void setProfession(java.lang.Integer profession) {
		set("profession", profession);
	}

	public java.lang.Integer getProfession() {
		return get("profession");
	}

	public void setSet(java.lang.Integer set) {
		set("set", set);
	}

	public java.lang.Integer getSet() {
		return get("set");
	}

	public void setBirthyear(java.lang.String birthyear) {
		set("birthyear", birthyear);
	}

	public java.lang.String getBirthyear() {
		return get("birthyear");
	}

	public void setBirthmonth(java.lang.String birthmonth) {
		set("birthmonth", birthmonth);
	}

	public java.lang.String getBirthmonth() {
		return get("birthmonth");
	}

	public void setBirthdate(java.lang.String birthdate) {
		set("birthdate", birthdate);
	}

	public java.lang.String getBirthdate() {
		return get("birthdate");
	}

	public void setInstId(java.lang.Integer instId) {
		set("inst_id", instId);
	}

	public java.lang.Integer getInstId() {
		return get("inst_id");
	}

}
