package wg.media.screen.fm.model.commandscreencommon.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseManageInstitution<M extends BaseManageInstitution<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	public java.lang.String getUuid() {
		return get("uuid");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setSystemCode(java.lang.Integer systemCode) {
		set("system_code", systemCode);
	}

	public java.lang.Integer getSystemCode() {
		return get("system_code");
	}

	public void setLeader(java.lang.String leader) {
		set("leader", leader);
	}

	public java.lang.String getLeader() {
		return get("leader");
	}

	public void setContacter(java.lang.String contacter) {
		set("contacter", contacter);
	}

	public java.lang.String getContacter() {
		return get("contacter");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}

	public java.lang.String getTelephone() {
		return get("telephone");
	}

	public void setFax(java.lang.String fax) {
		set("fax", fax);
	}

	public java.lang.String getFax() {
		return get("fax");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setZipCode(java.lang.String zipCode) {
		set("zip_code", zipCode);
	}

	public java.lang.String getZipCode() {
		return get("zip_code");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setWeb(java.lang.String web) {
		set("web", web);
	}

	public java.lang.String getWeb() {
		return get("web");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setDbIP(java.lang.String dbIP) {
		set("dbIP", dbIP);
	}

	public java.lang.String getDbIP() {
		return get("dbIP");
	}

	public void setDbindex(java.lang.Integer dbindex) {
		set("dbindex", dbindex);
	}

	public java.lang.Integer getDbindex() {
		return get("dbindex");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setSprintFlag(java.lang.String sprintFlag) {
		set("sprint_flag", sprintFlag);
	}

	public java.lang.String getSprintFlag() {
		return get("sprint_flag");
	}

	public void setCaibianHost(java.lang.String caibianHost) {
		set("caibian_host", caibianHost);
	}

	public java.lang.String getCaibianHost() {
		return get("caibian_host");
	}

	public void setLongitude(java.lang.Double longitude) {
		set("longitude", longitude);
	}

	public java.lang.Double getLongitude() {
		return get("longitude");
	}

	public void setLatitude(java.lang.Double latitude) {
		set("latitude", latitude);
	}

	public java.lang.Double getLatitude() {
		return get("latitude");
	}

	public void setAppId(java.lang.String appId) {
		set("app_id", appId);
	}

	public java.lang.String getAppId() {
		return get("app_id");
	}

	public void setAppSecret(java.lang.String appSecret) {
		set("app_secret", appSecret);
	}

	public java.lang.String getAppSecret() {
		return get("app_secret");
	}

	public void setJpushKey(java.lang.String jpushKey) {
		set("jpush_key", jpushKey);
	}

	public java.lang.String getJpushKey() {
		return get("jpush_key");
	}

	public void setJpushSecret(java.lang.String jpushSecret) {
		set("jpush_secret", jpushSecret);
	}

	public java.lang.String getJpushSecret() {
		return get("jpush_secret");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setPublicKey(java.lang.String publicKey) {
		set("public_key", publicKey);
	}

	public java.lang.String getPublicKey() {
		return get("public_key");
	}

	public void setPrivateKey(java.lang.String privateKey) {
		set("private_key", privateKey);
	}

	public java.lang.String getPrivateKey() {
		return get("private_key");
	}

	public void setTenentId(java.lang.Integer tenentId) {
		set("tenent_id", tenentId);
	}

	public java.lang.Integer getTenentId() {
		return get("tenent_id");
	}

}
