package wg.media.screen.fm.model.commandscreencommon.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseManageMedia<M extends BaseManageMedia<M>> extends Model<M> implements IBean {

	public void setMediaId(java.lang.Integer mediaId) {
		set("media_id", mediaId);
	}

	public java.lang.Integer getMediaId() {
		return get("media_id");
	}

	public void setMediaName(java.lang.String mediaName) {
		set("media_name", mediaName);
	}

	public java.lang.String getMediaName() {
		return get("media_name");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}

	public java.lang.String getIcon() {
		return get("icon");
	}

	public void setInstId(java.lang.Integer instId) {
		set("inst_id", instId);
	}

	public java.lang.Integer getInstId() {
		return get("inst_id");
	}

}
