package wg.media.screen.fm.model.commandscreencommon.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseImHistoryMessage<M extends BaseImHistoryMessage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setFingerPrint(java.lang.String fingerPrint) {
		set("fingerPrint", fingerPrint);
	}

	public java.lang.String getFingerPrint() {
		return get("fingerPrint");
	}

	public void setFromUserId(java.lang.String fromUserId) {
		set("from_user_id", fromUserId);
	}

	public java.lang.String getFromUserId() {
		return get("from_user_id");
	}

	public void setToUserId(java.lang.String toUserId) {
		set("to_user_id", toUserId);
	}

	public java.lang.String getToUserId() {
		return get("to_user_id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setCType(java.lang.Integer cType) {
		set("c_type", cType);
	}

	public java.lang.Integer getCType() {
		return get("c_type");
	}

	public void setUtype(java.lang.Integer utype) {
		set("utype", utype);
	}

	public java.lang.Integer getUtype() {
		return get("utype");
	}

	public void setSendNum(java.lang.Integer sendNum) {
		set("send_num", sendNum);
	}

	public java.lang.Integer getSendNum() {
		return get("send_num");
	}

	public void setSendStatus(java.lang.Integer sendStatus) {
		set("send_status", sendStatus);
	}

	public java.lang.Integer getSendStatus() {
		return get("send_status");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setSourceType(java.lang.Integer sourceType) {
		set("source_type", sourceType);
	}

	public java.lang.Integer getSourceType() {
		return get("source_type");
	}

	public void setSendTime(java.lang.String sendTime) {
		set("send_time", sendTime);
	}

	public java.lang.String getSendTime() {
		return get("send_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
