package wg.media.screen.fm.model.iam;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("iam_account", "id", IamAccount.class);
		arp.addMapping("iam_app", "app_id", IamApp.class);
		arp.addMapping("iam_caibian_user", "id", IamCaibianUser.class);
		arp.addMapping("iam_group", "group_id", IamGroup.class);
		arp.addMapping("iam_menu", "id", IamMenu.class);
		arp.addMapping("iam_pwd_policy", "policy_id", IamPwdPolicy.class);
		arp.addMapping("iam_role", "id", IamRole.class);
		arp.addMapping("iam_role_menu", "id", IamRoleMenu.class);
		arp.addMapping("iam_tenant", "id", IamTenant.class);
		arp.addMapping("iam_user", "id", IamUser.class);
		arp.addMapping("iam_user_role", "id", IamUserRole.class);
		arp.addMapping("iam_weak_password", "id", IamWeakPassword.class);
	}
}

