package wg.media.screen.fm.model.iam;

import wg.media.screen.fm.model.iam.base.BaseIamAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IamAccount extends BaseIamAccount<IamAccount> {
	public static final IamAccount dao = new IamAccount().dao();
}
