package wg.media.screen.fm.model.iam;

import wg.media.screen.fm.model.iam.base.BaseIamApp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IamApp extends BaseIamApp<IamApp> {
	public static final IamApp dao = new IamApp().dao();
}
