package wg.media.screen.fm.model.iam;

import wg.media.screen.fm.model.iam.base.BaseIamCaibianUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IamCaibianUser extends BaseIamCaibianUser<IamCaibianUser> {
	public static final IamCaibianUser dao = new IamCaibianUser().dao();
}
