package wg.media.screen.fm.model.iam;

import wg.media.screen.fm.model.iam.base.BaseIamGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IamGroup extends BaseIamGroup<IamGroup> {
	public static final IamGroup dao = new IamGroup().dao();
}
