package wg.media.screen.fm.model.iam;

import wg.media.screen.fm.model.iam.base.BaseIamMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IamMenu extends BaseIamMenu<IamMenu> {
	public static final IamMenu dao = new IamMenu().dao();
}
