package wg.media.screen.fm.model.iam;

import wg.media.screen.fm.model.iam.base.BaseIamPwdPolicy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IamPwdPolicy extends BaseIamPwdPolicy<IamPwdPolicy> {
	public static final IamPwdPolicy dao = new IamPwdPolicy().dao();
}
