package wg.media.screen.fm.model.iam;

import wg.media.screen.fm.model.iam.base.BaseIamRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IamRole extends BaseIamRole<IamRole> {
	public static final IamRole dao = new IamRole().dao();
}
