package wg.media.screen.fm.model.iam;

import wg.media.screen.fm.model.iam.base.BaseIamRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IamRoleMenu extends BaseIamRoleMenu<IamRoleMenu> {
	public static final IamRoleMenu dao = new IamRoleMenu().dao();
}
