package wg.media.screen.fm.model.iam;

import wg.media.screen.fm.model.iam.base.BaseIamTenant;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IamTenant extends BaseIamTenant<IamTenant> {
	public static final IamTenant dao = new IamTenant().dao();
}
