package wg.media.screen.fm.model.iam;

import wg.media.screen.fm.model.iam.base.BaseIamUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IamUserRole extends BaseIamUserRole<IamUserRole> {
	public static final IamUserRole dao = new IamUserRole().dao();
}
