package wg.media.screen.fm.model.iam;

import wg.media.screen.fm.model.iam.base.BaseIamUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IamUser extends BaseIamUser<IamUser> {
	public static final IamUser dao = new IamUser().dao();
}
