package wg.media.screen.fm.model.iam;

import wg.media.screen.fm.model.iam.base.BaseIamWeakPassword;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IamWeakPassword extends BaseIamWeakPassword<IamWeakPassword> {
	public static final IamWeakPassword dao = new IamWeakPassword().dao();
}
