package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNoticeLog<M extends BaseNoticeLog<M>> extends Model<M> implements IBean {

	public void setNId(java.lang.Integer nId) {
		set("n_id", nId);
	}

	public java.lang.Integer getNId() {
		return get("n_id");
	}

	public void setReadPerson(java.lang.String readPerson) {
		set("read_person", readPerson);
	}

	public java.lang.String getReadPerson() {
		return get("read_person");
	}

	public void setBelongToTopic(java.lang.String belongToTopic) {
		set("belong_to_topic", belongToTopic);
	}

	public java.lang.String getBelongToTopic() {
		return get("belong_to_topic");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setNoticeId(java.lang.Integer noticeId) {
		set("notice_id", noticeId);
	}

	public java.lang.Integer getNoticeId() {
		return get("notice_id");
	}

	public void setReadTime(java.util.Date readTime) {
		set("read_time", readTime);
	}

	public java.util.Date getReadTime() {
		return get("read_time");
	}

}
