package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRedDot<M extends BaseRedDot<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCreatePsnId(java.lang.Integer createPsnId) {
		set("create_psn_id", createPsnId);
	}

	public java.lang.Integer getCreatePsnId() {
		return get("create_psn_id");
	}

	public void setReceivePsnId(java.lang.Integer receivePsnId) {
		set("receive_psn_id", receivePsnId);
	}

	public java.lang.Integer getReceivePsnId() {
		return get("receive_psn_id");
	}

	public void setDataType(java.lang.Integer dataType) {
		set("data_type", dataType);
	}

	public java.lang.Integer getDataType() {
		return get("data_type");
	}

	public void setDataId(java.lang.Integer dataId) {
		set("data_id", dataId);
	}

	public java.lang.Integer getDataId() {
		return get("data_id");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setReadTime(java.util.Date readTime) {
		set("read_time", readTime);
	}

	public java.util.Date getReadTime() {
		return get("read_time");
	}

	public void setBelongToTopic(java.lang.Integer belongToTopic) {
		set("belong_to_topic", belongToTopic);
	}

	public java.lang.Integer getBelongToTopic() {
		return get("belong_to_topic");
	}

}
