package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDraft<M extends BaseDraft<M>> extends Model<M> implements IBean {

	public void setDId(java.lang.Integer dId) {
		set("d_id", dId);
	}

	public java.lang.Integer getDId() {
		return get("d_id");
	}

	public void setDraftName(java.lang.String draftName) {
		set("draft_name", draftName);
	}

	public java.lang.String getDraftName() {
		return get("draft_name");
	}

	public void setDraftTheme(java.lang.String draftTheme) {
		set("draft_theme", draftTheme);
	}

	public java.lang.String getDraftTheme() {
		return get("draft_theme");
	}

	public void setDraftContent(java.lang.String draftContent) {
		set("draft_content", draftContent);
	}

	public java.lang.String getDraftContent() {
		return get("draft_content");
	}

	public void setBelongToMedia(java.lang.String belongToMedia) {
		set("belong_to_media", belongToMedia);
	}

	public java.lang.String getBelongToMedia() {
		return get("belong_to_media");
	}

	public void setUploadTime(java.util.Date uploadTime) {
		set("upload_time", uploadTime);
	}

	public java.util.Date getUploadTime() {
		return get("upload_time");
	}

	public void setDraftType(java.lang.String draftType) {
		set("draft_type", draftType);
	}

	public java.lang.String getDraftType() {
		return get("draft_type");
	}

	public void setDraftStatus(java.lang.String draftStatus) {
		set("draft_status", draftStatus);
	}

	public java.lang.String getDraftStatus() {
		return get("draft_status");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}

	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public void setDraftPath(java.lang.String draftPath) {
		set("draft_path", draftPath);
	}

	public java.lang.String getDraftPath() {
		return get("draft_path");
	}

	public void setDraftPublishPlatform(java.lang.String draftPublishPlatform) {
		set("draft_publish_platform", draftPublishPlatform);
	}

	public java.lang.String getDraftPublishPlatform() {
		return get("draft_publish_platform");
	}

	public void setAuditor(java.lang.String auditor) {
		set("auditor", auditor);
	}

	public java.lang.String getAuditor() {
		return get("auditor");
	}

	public void setBelongToTopic(java.lang.String belongToTopic) {
		set("belong_to_topic", belongToTopic);
	}

	public java.lang.String getBelongToTopic() {
		return get("belong_to_topic");
	}

	public void setUploadPerson(java.lang.Integer uploadPerson) {
		set("upload_person", uploadPerson);
	}

	public java.lang.Integer getUploadPerson() {
		return get("upload_person");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setIsSend(java.lang.Integer isSend) {
		set("is_send", isSend);
	}

	public java.lang.Integer getIsSend() {
		return get("is_send");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

}
