package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNoticeData<M extends BaseNoticeData<M>> extends Model<M> implements IBean {

	public void setNId(java.lang.Integer nId) {
		set("n_id", nId);
	}

	public java.lang.Integer getNId() {
		return get("n_id");
	}

	public void setNoticeDataTitle(java.lang.String noticeDataTitle) {
		set("notice_data_title", noticeDataTitle);
	}

	public java.lang.String getNoticeDataTitle() {
		return get("notice_data_title");
	}

	public void setNoticeDataContent(java.lang.String noticeDataContent) {
		set("notice_data_content", noticeDataContent);
	}

	public java.lang.String getNoticeDataContent() {
		return get("notice_data_content");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setNoticeDataParticipant(java.lang.String noticeDataParticipant) {
		set("notice_data_participant", noticeDataParticipant);
	}

	public java.lang.String getNoticeDataParticipant() {
		return get("notice_data_participant");
	}

	public void setNoticeDataCreator(java.lang.String noticeDataCreator) {
		set("notice_data_creator", noticeDataCreator);
	}

	public java.lang.String getNoticeDataCreator() {
		return get("notice_data_creator");
	}

	public void setNoticeDataStatus(java.lang.String noticeDataStatus) {
		set("notice_data_status", noticeDataStatus);
	}

	public java.lang.String getNoticeDataStatus() {
		return get("notice_data_status");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}

	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

}
