package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTaskLog<M extends BaseTaskLog<M>> extends Model<M> implements IBean {

	public void setTId(java.lang.Integer tId) {
		set("t_id", tId);
	}

	public java.lang.Integer getTId() {
		return get("t_id");
	}

	public void setTaskId(java.lang.Integer taskId) {
		set("task_id", taskId);
	}

	public java.lang.Integer getTaskId() {
		return get("task_id");
	}

	public void setPersonalId(java.lang.Integer personalId) {
		set("personal_id", personalId);
	}

	public java.lang.Integer getPersonalId() {
		return get("personal_id");
	}

	public void setPersonalType(java.lang.String personalType) {
		set("personal_type", personalType);
	}

	public java.lang.String getPersonalType() {
		return get("personal_type");
	}

	public void setOperationalDesc(java.lang.String operationalDesc) {
		set("operational_desc", operationalDesc);
	}

	public java.lang.String getOperationalDesc() {
		return get("operational_desc");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setEnclosureName(java.lang.String enclosureName) {
		set("enclosure_name", enclosureName);
	}

	public java.lang.String getEnclosureName() {
		return get("enclosure_name");
	}

	public void setEnclosurePath(java.lang.String enclosurePath) {
		set("enclosure_path", enclosurePath);
	}

	public java.lang.String getEnclosurePath() {
		return get("enclosure_path");
	}

	public void setFileId(java.lang.Integer fileId) {
		set("file_id", fileId);
	}

	public java.lang.Integer getFileId() {
		return get("file_id");
	}

	public void setProType(java.lang.Integer proType) {
		set("pro_type", proType);
	}

	public java.lang.Integer getProType() {
		return get("pro_type");
	}

}
