package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArchiveFile<M extends BaseArchiveFile<M>> extends Model<M> implements IBean {

	public void setFileId(java.lang.Integer fileId) {
		set("file_id", fileId);
	}

	public java.lang.Integer getFileId() {
		return get("file_id");
	}

	public void setFileName(java.lang.String fileName) {
		set("file_name", fileName);
	}

	public java.lang.String getFileName() {
		return get("file_name");
	}

	public void setDataType(java.lang.String dataType) {
		set("data_type", dataType);
	}

	public java.lang.String getDataType() {
		return get("data_type");
	}

	public void setFileDesc(java.lang.String fileDesc) {
		set("file_desc", fileDesc);
	}

	public java.lang.String getFileDesc() {
		return get("file_desc");
	}

	public void setFilePath(java.lang.String filePath) {
		set("file_path", filePath);
	}

	public java.lang.String getFilePath() {
		return get("file_path");
	}

	public void setCreatePsnId(java.lang.String createPsnId) {
		set("create_psn_id", createPsnId);
	}

	public java.lang.String getCreatePsnId() {
		return get("create_psn_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setFileSize(java.lang.Double fileSize) {
		set("file_size", fileSize);
	}

	public java.lang.Double getFileSize() {
		return get("file_size");
	}

	public void setFileExt(java.lang.String fileExt) {
		set("file_ext", fileExt);
	}

	public java.lang.String getFileExt() {
		return get("file_ext");
	}

	public void setContentType(java.lang.String contentType) {
		set("content_type", contentType);
	}

	public java.lang.String getContentType() {
		return get("content_type");
	}

	public void setThumbnailPath(java.lang.String thumbnailPath) {
		set("thumbnail_path", thumbnailPath);
	}

	public java.lang.String getThumbnailPath() {
		return get("thumbnail_path");
	}

}
