package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNoticeComments<M extends BaseNoticeComments<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCommentsPsnId(java.lang.Integer commentsPsnId) {
		set("comments_psn_id", commentsPsnId);
	}

	public java.lang.Integer getCommentsPsnId() {
		return get("comments_psn_id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setNoticeId(java.lang.Integer noticeId) {
		set("notice_id", noticeId);
	}

	public java.lang.Integer getNoticeId() {
		return get("notice_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
