package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpenConfig<M extends BaseOpenConfig<M>> extends Model<M> implements IBean {

	public void setAutoId(java.math.BigInteger autoId) {
		set("auto_id", autoId);
	}

	public java.math.BigInteger getAutoId() {
		return get("auto_id");
	}

	public void setSubSystemName(java.lang.String subSystemName) {
		set("sub_system_name", subSystemName);
	}

	public java.lang.String getSubSystemName() {
		return get("sub_system_name");
	}

	public void setSystemCode(java.lang.Integer systemCode) {
		set("system_code", systemCode);
	}

	public java.lang.Integer getSystemCode() {
		return get("system_code");
	}

	public void setAppId(java.lang.String appId) {
		set("app_id", appId);
	}

	public java.lang.String getAppId() {
		return get("app_id");
	}

	public void setAppSecret(java.lang.String appSecret) {
		set("app_secret", appSecret);
	}

	public java.lang.String getAppSecret() {
		return get("app_secret");
	}

	public void setTokenUrl(java.lang.String tokenUrl) {
		set("token_url", tokenUrl);
	}

	public java.lang.String getTokenUrl() {
		return get("token_url");
	}

	public void setInsertTime(java.util.Date insertTime) {
		set("insert_time", insertTime);
	}

	public java.util.Date getInsertTime() {
		return get("insert_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
