package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppVersion<M extends BaseAppVersion<M>> extends Model<M> implements IBean {

	public void setAutoId(java.lang.Integer autoId) {
		set("auto_id", autoId);
	}

	public java.lang.Integer getAutoId() {
		return get("auto_id");
	}

	public void setAppVersion(java.lang.String appVersion) {
		set("app_version", appVersion);
	}

	public java.lang.String getAppVersion() {
		return get("app_version");
	}

	public void setAppPath(java.lang.String appPath) {
		set("app_path", appPath);
	}

	public java.lang.String getAppPath() {
		return get("app_path");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setInsertTime(java.util.Date insertTime) {
		set("insert_time", insertTime);
	}

	public java.util.Date getInsertTime() {
		return get("insert_time");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setIosUpdate(java.lang.String iosUpdate) {
		set("iosUpdate", iosUpdate);
	}

	public java.lang.String getIosUpdate() {
		return get("iosUpdate");
	}

	public void setIosMsg(java.lang.String iosMsg) {
		set("iosMsg", iosMsg);
	}

	public java.lang.String getIosMsg() {
		return get("iosMsg");
	}

	public void setVersionCode(java.lang.Integer versionCode) {
		set("version_code", versionCode);
	}

	public java.lang.Integer getVersionCode() {
		return get("version_code");
	}

}
