package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConstDictionary<M extends BaseConstDictionary<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCategory(java.lang.String category) {
		set("category", category);
	}

	public java.lang.String getCategory() {
		return get("category");
	}

	public void setCategoryCode(java.lang.String categoryCode) {
		set("category_code", categoryCode);
	}

	public java.lang.String getCategoryCode() {
		return get("category_code");
	}

	public void setCategoryName(java.lang.String categoryName) {
		set("category_name", categoryName);
	}

	public java.lang.String getCategoryName() {
		return get("category_name");
	}

	public void setCategoryValue(java.lang.String categoryValue) {
		set("category_value", categoryValue);
	}

	public java.lang.String getCategoryValue() {
		return get("category_value");
	}

	public void setSeqNo(java.lang.Integer seqNo) {
		set("seq_no", seqNo);
	}

	public java.lang.Integer getSeqNo() {
		return get("seq_no");
	}

}
