package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpenRefUserInvoke<M extends BaseOpenRefUserInvoke<M>> extends Model<M> implements IBean {

	public void setAutoId(java.math.BigInteger autoId) {
		set("auto_id", autoId);
	}

	public java.math.BigInteger getAutoId() {
		return get("auto_id");
	}

	public void setInstId(java.lang.Integer instId) {
		set("inst_id", instId);
	}

	public java.lang.Integer getInstId() {
		return get("inst_id");
	}

	public void setOpenInvokeId(java.lang.Long openInvokeId) {
		set("open_invoke_id", openInvokeId);
	}

	public java.lang.Long getOpenInvokeId() {
		return get("open_invoke_id");
	}

	public void setRequestParam(java.lang.String requestParam) {
		set("requestParam", requestParam);
	}

	public java.lang.String getRequestParam() {
		return get("requestParam");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

}
