package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpenLayout<M extends BaseOpenLayout<M>> extends Model<M> implements IBean {

	public void setAutoId(java.math.BigInteger autoId) {
		set("auto_id", autoId);
	}

	public java.math.BigInteger getAutoId() {
		return get("auto_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setInstId(java.lang.Long instId) {
		set("inst_id", instId);
	}

	public java.lang.Long getInstId() {
		return get("inst_id");
	}

	public void setLayout(java.lang.String layout) {
		set("layout", layout);
	}

	public java.lang.String getLayout() {
		return get("layout");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setInsertTime(java.util.Date insertTime) {
		set("insert_time", insertTime);
	}

	public java.util.Date getInsertTime() {
		return get("insert_time");
	}

}
