package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTask<M extends BaseTask<M>> extends Model<M> implements IBean {

	public void setTId(java.lang.Integer tId) {
		set("t_id", tId);
	}

	public java.lang.Integer getTId() {
		return get("t_id");
	}

	public void setTaskTitle(java.lang.String taskTitle) {
		set("task_title", taskTitle);
	}

	public java.lang.String getTaskTitle() {
		return get("task_title");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}

	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public void setTaskDescription(java.lang.String taskDescription) {
		set("task_description", taskDescription);
	}

	public java.lang.String getTaskDescription() {
		return get("task_description");
	}

	public void setTaskCreator(java.lang.String taskCreator) {
		set("task_creator", taskCreator);
	}

	public java.lang.String getTaskCreator() {
		return get("task_creator");
	}

	public void setTaskPrincipal(java.lang.String taskPrincipal) {
		set("task_principal", taskPrincipal);
	}

	public java.lang.String getTaskPrincipal() {
		return get("task_principal");
	}

	public void setTaskParticipant(java.lang.String taskParticipant) {
		set("task_participant", taskParticipant);
	}

	public java.lang.String getTaskParticipant() {
		return get("task_participant");
	}

	public void setTaskProgress(java.lang.String taskProgress) {
		set("task_progress", taskProgress);
	}

	public java.lang.String getTaskProgress() {
		return get("task_progress");
	}

	public void setTaskStarttime(java.util.Date taskStarttime) {
		set("task_startTime", taskStarttime);
	}

	public java.util.Date getTaskStarttime() {
		return get("task_startTime");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setTaskStatus(java.lang.String taskStatus) {
		set("task_status", taskStatus);
	}

	public java.lang.String getTaskStatus() {
		return get("task_status");
	}

	public void setBelongToTopic(java.lang.String belongToTopic) {
		set("belong_to_topic", belongToTopic);
	}

	public java.lang.String getBelongToTopic() {
		return get("belong_to_topic");
	}

	public void setTaskEndtime(java.util.Date taskEndtime) {
		set("task_endTime", taskEndtime);
	}

	public java.util.Date getTaskEndtime() {
		return get("task_endTime");
	}

	public void setTaskLevel(java.lang.String taskLevel) {
		set("task_level", taskLevel);
	}

	public java.lang.String getTaskLevel() {
		return get("task_level");
	}

	public void setMediaId(java.lang.Integer mediaId) {
		set("media_id", mediaId);
	}

	public java.lang.Integer getMediaId() {
		return get("media_id");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setDelayStatus(java.lang.Integer delayStatus) {
		set("delay_status", delayStatus);
	}

	public java.lang.Integer getDelayStatus() {
		return get("delay_status");
	}

}
