package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpenModule<M extends BaseOpenModule<M>> extends Model<M> implements IBean {

	public void setAutoId(java.lang.Long autoId) {
		set("auto_id", autoId);
	}

	public java.lang.Long getAutoId() {
		return get("auto_id");
	}

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setText(java.lang.String text) {
		set("text", text);
	}

	public java.lang.String getText() {
		return get("text");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setDataApiUrl(java.lang.String dataApiUrl) {
		set("dataApiUrl", dataApiUrl);
	}

	public java.lang.String getDataApiUrl() {
		return get("dataApiUrl");
	}

	public void setInsertTime(java.util.Date insertTime) {
		set("insert_time", insertTime);
	}

	public java.util.Date getInsertTime() {
		return get("insert_time");
	}

}
