package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMediaDraftnum<M extends BaseMediaDraftnum<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTId(java.lang.Integer tId) {
		set("t_id", tId);
	}

	public java.lang.Integer getTId() {
		return get("t_id");
	}

	public void setMedia(java.lang.String media) {
		set("media", media);
	}

	public java.lang.String getMedia() {
		return get("media");
	}

	public void setWebNum(java.lang.String webNum) {
		set("web_num", webNum);
	}

	public java.lang.String getWebNum() {
		return get("web_num");
	}

	public void setWechatNum(java.lang.String wechatNum) {
		set("wechat_num", wechatNum);
	}

	public java.lang.String getWechatNum() {
		return get("wechat_num");
	}

	public void setPaperNum(java.lang.String paperNum) {
		set("paper_num", paperNum);
	}

	public java.lang.String getPaperNum() {
		return get("paper_num");
	}

	public void setWeiboNum(java.lang.String weiboNum) {
		set("weibo_num", weiboNum);
	}

	public java.lang.String getWeiboNum() {
		return get("weibo_num");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
