package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductsAnalysis<M extends BaseProductsAnalysis<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setInsName(java.lang.String insName) {
		set("ins_name", insName);
	}

	public java.lang.String getInsName() {
		return get("ins_name");
	}

	public void setInsId(java.lang.Integer insId) {
		set("ins_id", insId);
	}

	public java.lang.Integer getInsId() {
		return get("ins_id");
	}

	public void setMediaId(java.lang.Integer mediaId) {
		set("media_id", mediaId);
	}

	public java.lang.Integer getMediaId() {
		return get("media_id");
	}

	public void setMediaName(java.lang.String mediaName) {
		set("media_name", mediaName);
	}

	public java.lang.String getMediaName() {
		return get("media_name");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
