package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseManageClientVideo<M extends BaseManageClientVideo<M>> extends Model<M> implements IBean {

	public void setAutoId(java.lang.Long autoId) {
		set("auto_id", autoId);
	}

	public java.lang.Long getAutoId() {
		return get("auto_id");
	}

	public void setLink(java.lang.String link) {
		set("link", link);
	}

	public java.lang.String getLink() {
		return get("link");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setInstId(java.lang.Long instId) {
		set("inst_id", instId);
	}

	public java.lang.Long getInstId() {
		return get("inst_id");
	}

}
