package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNotice<M extends BaseNotice<M>> extends Model<M> implements IBean {

	public void setNId(java.lang.Integer nId) {
		set("n_id", nId);
	}

	public java.lang.Integer getNId() {
		return get("n_id");
	}

	public void setNoticeName(java.lang.String noticeName) {
		set("notice_name", noticeName);
	}

	public java.lang.String getNoticeName() {
		return get("notice_name");
	}

	public void setNoticeDesc(java.lang.String noticeDesc) {
		set("notice_desc", noticeDesc);
	}

	public java.lang.String getNoticeDesc() {
		return get("notice_desc");
	}

	public void setNoticeParticipant(java.lang.String noticeParticipant) {
		set("notice_participant", noticeParticipant);
	}

	public java.lang.String getNoticeParticipant() {
		return get("notice_participant");
	}

	public void setNoticePrincipal(java.lang.String noticePrincipal) {
		set("notice_principal", noticePrincipal);
	}

	public java.lang.String getNoticePrincipal() {
		return get("notice_principal");
	}

	public void setNoticeLevel(java.lang.String noticeLevel) {
		set("notice_level", noticeLevel);
	}

	public java.lang.String getNoticeLevel() {
		return get("notice_level");
	}

	public void setNoticeStatus(java.lang.String noticeStatus) {
		set("notice_status", noticeStatus);
	}

	public java.lang.String getNoticeStatus() {
		return get("notice_status");
	}

	public void setNoticeDays(java.lang.String noticeDays) {
		set("notice_days", noticeDays);
	}

	public java.lang.String getNoticeDays() {
		return get("notice_days");
	}

	public void setBelongToTopic(java.lang.String belongToTopic) {
		set("belong_to_topic", belongToTopic);
	}

	public java.lang.String getBelongToTopic() {
		return get("belong_to_topic");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}

	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

}
