package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTaskMember<M extends BaseTaskMember<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTId(java.lang.Integer tId) {
		set("t_id", tId);
	}

	public java.lang.Integer getTId() {
		return get("t_id");
	}

	public void setMemberPsnId(java.lang.Integer memberPsnId) {
		set("member_psn_id", memberPsnId);
	}

	public java.lang.Integer getMemberPsnId() {
		return get("member_psn_id");
	}

	public void setMemberPsnName(java.lang.String memberPsnName) {
		set("member_psn_name", memberPsnName);
	}

	public java.lang.String getMemberPsnName() {
		return get("member_psn_name");
	}

	public void setIsPrincipal(java.lang.Integer isPrincipal) {
		set("is_principal", isPrincipal);
	}

	public java.lang.Integer getIsPrincipal() {
		return get("is_principal");
	}

	public void setSeqNo(java.lang.Integer seqNo) {
		set("seq_no", seqNo);
	}

	public java.lang.Integer getSeqNo() {
		return get("seq_no");
	}

}
