package wg.media.screen.fm.model.commandscreen.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSource<M extends BaseSource<M>> extends Model<M> implements IBean {

	public void setSId(java.lang.Integer sId) {
		set("s_id", sId);
	}

	public java.lang.Integer getSId() {
		return get("s_id");
	}

	public void setSourceName(java.lang.String sourceName) {
		set("source_name", sourceName);
	}

	public java.lang.String getSourceName() {
		return get("source_name");
	}

	public void setUploadTime(java.util.Date uploadTime) {
		set("upload_time", uploadTime);
	}

	public java.util.Date getUploadTime() {
		return get("upload_time");
	}

	public void setSourceType(java.lang.String sourceType) {
		set("source_type", sourceType);
	}

	public java.lang.String getSourceType() {
		return get("source_type");
	}

	public void setSourcePath(java.lang.String sourcePath) {
		set("source_path", sourcePath);
	}

	public java.lang.String getSourcePath() {
		return get("source_path");
	}

	public void setUploadPerson(java.lang.String uploadPerson) {
		set("upload_person", uploadPerson);
	}

	public java.lang.String getUploadPerson() {
		return get("upload_person");
	}

	public void setSourceDesc(java.lang.String sourceDesc) {
		set("source_desc", sourceDesc);
	}

	public java.lang.String getSourceDesc() {
		return get("source_desc");
	}

	public void setSourceStatus(java.lang.String sourceStatus) {
		set("source_status", sourceStatus);
	}

	public java.lang.String getSourceStatus() {
		return get("source_status");
	}

	public void setBelongToTopic(java.lang.String belongToTopic) {
		set("belong_to_topic", belongToTopic);
	}

	public java.lang.String getBelongToTopic() {
		return get("belong_to_topic");
	}

	public void setBelongToMedia(java.lang.String belongToMedia) {
		set("belong_to_media", belongToMedia);
	}

	public java.lang.String getBelongToMedia() {
		return get("belong_to_media");
	}

	public void setSourceLabel(java.lang.String sourceLabel) {
		set("source_label", sourceLabel);
	}

	public java.lang.String getSourceLabel() {
		return get("source_label");
	}

	public void setRead(java.lang.Integer read) {
		set("read", read);
	}

	public java.lang.Integer getRead() {
		return get("read");
	}

	public void setDownload(java.lang.Integer download) {
		set("download", download);
	}

	public java.lang.Integer getDownload() {
		return get("download");
	}

	public void setIsPush(java.lang.Integer isPush) {
		set("is_push", isPush);
	}

	public java.lang.Integer getIsPush() {
		return get("is_push");
	}

}
