package wg.media.screen.fm.model.iam.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIamAccount<M extends BaseIamAccount<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

	public void setAccountId(java.lang.Long accountId) {
		set("account_id", accountId);
	}

	public java.lang.Long getAccountId() {
		return get("account_id");
	}

	public void setAppId(java.lang.Long appId) {
		set("appId", appId);
	}

	public java.lang.Long getAppId() {
		return get("appId");
	}

	public void setEnable(java.lang.Boolean enable) {
		set("enable", enable);
	}

	public java.lang.Boolean getEnable() {
		return get("enable");
	}

	public void setAppName(java.lang.String appName) {
		set("app_name", appName);
	}

	public java.lang.String getAppName() {
		return get("app_name");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

}
