package wg.media.screen.fm.model.iam.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIamCaibianUser<M extends BaseIamCaibianUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setTenentId(java.lang.Integer tenentId) {
		set("tenent_id", tenentId);
	}

	public java.lang.Integer getTenentId() {
		return get("tenent_id");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public void setCaibianUsername(java.lang.String caibianUsername) {
		set("caibian_username", caibianUsername);
	}

	public java.lang.String getCaibianUsername() {
		return get("caibian_username");
	}

	public void setCaibianPwd(java.lang.String caibianPwd) {
		set("caibian_pwd", caibianPwd);
	}

	public java.lang.String getCaibianPwd() {
		return get("caibian_pwd");
	}

	public void setInsertTime(java.util.Date insertTime) {
		set("insert_time", insertTime);
	}

	public java.util.Date getInsertTime() {
		return get("insert_time");
	}

}
