package wg.media.screen.fm.model.iam.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIamGroup<M extends BaseIamGroup<M>> extends Model<M> implements IBean {

	public void setGroupId(java.lang.Long groupId) {
		set("group_id", groupId);
	}

	public java.lang.Long getGroupId() {
		return get("group_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setLevel(java.lang.String level) {
		set("level", level);
	}

	public java.lang.String getLevel() {
		return get("level");
	}

	public void setParentGroupId(java.math.BigInteger parentGroupId) {
		set("parent_group_id", parentGroupId);
	}

	public java.math.BigInteger getParentGroupId() {
		return get("parent_group_id");
	}

	public void setSeq(java.math.BigInteger seq) {
		set("seq", seq);
	}

	public java.math.BigInteger getSeq() {
		return get("seq");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateUser(java.math.BigInteger updateUser) {
		set("update_user", updateUser);
	}

	public java.math.BigInteger getUpdateUser() {
		return get("update_user");
	}

	public void setCreateUser(java.math.BigInteger createUser) {
		set("create_user", createUser);
	}

	public java.math.BigInteger getCreateUser() {
		return get("create_user");
	}

	public void setEnable(java.lang.Boolean enable) {
		set("enable", enable);
	}

	public java.lang.Boolean getEnable() {
		return get("enable");
	}

	public void setTenentId(java.lang.Integer tenentId) {
		set("tenent_id", tenentId);
	}

	public java.lang.Integer getTenentId() {
		return get("tenent_id");
	}

}
