package wg.media.screen.fm.model.iam.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIamApp<M extends BaseIamApp<M>> extends Model<M> implements IBean {

	public void setAppId(java.lang.Long appId) {
		set("app_id", appId);
	}

	public java.lang.Long getAppId() {
		return get("app_id");
	}

	public void setAppName(java.lang.String appName) {
		set("app_name", appName);
	}

	public java.lang.String getAppName() {
		return get("app_name");
	}

	public void setServerApiKey(java.lang.String serverApiKey) {
		set("server_api_Key", serverApiKey);
	}

	public java.lang.String getServerApiKey() {
		return get("server_api_Key");
	}

	public void setClientApiKey(java.lang.String clientApiKey) {
		set("client_api_key", clientApiKey);
	}

	public java.lang.String getClientApiKey() {
		return get("client_api_key");
	}

	public void setEnabled(java.lang.Boolean enabled) {
		set("enabled", enabled);
	}

	public java.lang.Boolean getEnabled() {
		return get("enabled");
	}

	public void setStrategyId(java.lang.Integer strategyId) {
		set("strategy_id", strategyId);
	}

	public java.lang.Integer getStrategyId() {
		return get("strategy_id");
	}

	public void setOwnerId(java.lang.Long ownerId) {
		set("owner_id", ownerId);
	}

	public java.lang.Long getOwnerId() {
		return get("owner_id");
	}

	public void setAppCode(java.lang.String appCode) {
		set("app_code", appCode);
	}

	public java.lang.String getAppCode() {
		return get("app_code");
	}

	public void setClientType(java.lang.String clientType) {
		set("client_type", clientType);
	}

	public java.lang.String getClientType() {
		return get("client_type");
	}

	public void setSsoType(java.lang.String ssoType) {
		set("sso_Type", ssoType);
	}

	public java.lang.String getSsoType() {
		return get("sso_Type");
	}

	public void setLogoutUrl(java.lang.String logoutUrl) {
		set("logout_url", logoutUrl);
	}

	public java.lang.String getLogoutUrl() {
		return get("logout_url");
	}

	public void setDecritpion(java.lang.String decritpion) {
		set("decritpion", decritpion);
	}

	public java.lang.String getDecritpion() {
		return get("decritpion");
	}

	public void setIsWhite(java.lang.Boolean isWhite) {
		set("is_white", isWhite);
	}

	public java.lang.Boolean getIsWhite() {
		return get("is_white");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setMainUrl(java.lang.String mainUrl) {
		set("main_url", mainUrl);
	}

	public java.lang.String getMainUrl() {
		return get("main_url");
	}

	public void setService(java.lang.String service) {
		set("service", service);
	}

	public java.lang.String getService() {
		return get("service");
	}

	public void setImageUrl(java.lang.String imageUrl) {
		set("image_url", imageUrl);
	}

	public java.lang.String getImageUrl() {
		return get("image_url");
	}

}
