package wg.media.screen.fm.model.iam.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIamTenant<M extends BaseIamTenant<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTenant(java.lang.String tenant) {
		set("tenant", tenant);
	}

	public java.lang.String getTenant() {
		return get("tenant");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setEnable(java.lang.Boolean enable) {
		set("enable", enable);
	}

	public java.lang.Boolean getEnable() {
		return get("enable");
	}

	public void setOwnerId(java.lang.Long ownerId) {
		set("owner_id", ownerId);
	}

	public java.lang.Long getOwnerId() {
		return get("owner_id");
	}

	public void setOwnerName(java.lang.String ownerName) {
		set("owner_name", ownerName);
	}

	public java.lang.String getOwnerName() {
		return get("owner_name");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setContacts(java.lang.String contacts) {
		set("contacts", contacts);
	}

	public java.lang.String getContacts() {
		return get("contacts");
	}

	public void setContactsInfo(java.lang.String contactsInfo) {
		set("contacts_info", contactsInfo);
	}

	public java.lang.String getContactsInfo() {
		return get("contacts_info");
	}

}
