package wg.media.screen.fm.model.iam.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIamMenu<M extends BaseIamMenu<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setMenuPid(java.lang.Integer menuPid) {
		set("menu_pid", menuPid);
	}

	public java.lang.Integer getMenuPid() {
		return get("menu_pid");
	}

	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}

	public java.lang.Boolean getStatus() {
		return get("status");
	}

	public void setMenuType(java.lang.Integer menuType) {
		set("menu_type", menuType);
	}

	public java.lang.Integer getMenuType() {
		return get("menu_type");
	}

	public void setHref(java.lang.String href) {
		set("href", href);
	}

	public java.lang.String getHref() {
		return get("href");
	}

	public void setMenuCode(java.lang.String menuCode) {
		set("menu_code", menuCode);
	}

	public java.lang.String getMenuCode() {
		return get("menu_code");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
