package wg.media.screen.fm.model.iam.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIamUser<M extends BaseIamUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public void setDispalyName(java.lang.String dispalyName) {
		set("dispaly_name", dispalyName);
	}

	public java.lang.String getDispalyName() {
		return get("dispaly_name");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setGroupId(java.lang.Long groupId) {
		set("group_id", groupId);
	}

	public java.lang.Long getGroupId() {
		return get("group_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setValidateTime(java.util.Date validateTime) {
		set("validate_time", validateTime);
	}

	public java.util.Date getValidateTime() {
		return get("validate_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdatePwdTime(java.util.Date updatePwdTime) {
		set("update_pwd_time", updatePwdTime);
	}

	public java.util.Date getUpdatePwdTime() {
		return get("update_pwd_time");
	}

	public void setOwnerId(java.lang.Long ownerId) {
		set("owner_id", ownerId);
	}

	public java.lang.Long getOwnerId() {
		return get("owner_id");
	}

	public void setTenentId(java.lang.Integer tenentId) {
		set("tenent_id", tenentId);
	}

	public java.lang.Integer getTenentId() {
		return get("tenent_id");
	}

	public void setPwdId(java.lang.Integer pwdId) {
		set("pwd_id", pwdId);
	}

	public java.lang.Integer getPwdId() {
		return get("pwd_id");
	}

}
