package wg.media.screen.fm.model.iam.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIamRole<M extends BaseIamRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setRoleName(java.lang.String roleName) {
		set("role_name", roleName);
	}

	public java.lang.String getRoleName() {
		return get("role_name");
	}

	public void setRolePid(java.lang.Integer rolePid) {
		set("role_pid", rolePid);
	}

	public java.lang.Integer getRolePid() {
		return get("role_pid");
	}

	public void setEnabled(java.lang.Boolean enabled) {
		set("enabled", enabled);
	}

	public java.lang.Boolean getEnabled() {
		return get("enabled");
	}

	public void setRoleCode(java.lang.String roleCode) {
		set("role_code", roleCode);
	}

	public java.lang.String getRoleCode() {
		return get("role_code");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
