package wg.media.screen.fm.model.iam.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIamPwdPolicy<M extends BaseIamPwdPolicy<M>> extends Model<M> implements IBean {

	public void setPolicyId(java.lang.Integer policyId) {
		set("policy_id", policyId);
	}

	public java.lang.Integer getPolicyId() {
		return get("policy_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setEnable(java.lang.Boolean enable) {
		set("enable", enable);
	}

	public java.lang.Boolean getEnable() {
		return get("enable");
	}

	public void setBanned(java.lang.Boolean banned) {
		set("banned", banned);
	}

	public java.lang.Boolean getBanned() {
		return get("banned");
	}

	public void setMin(java.lang.Integer min) {
		set("min", min);
	}

	public java.lang.Integer getMin() {
		return get("min");
	}

	public void setMax(java.lang.Integer max) {
		set("max", max);
	}

	public java.lang.Integer getMax() {
		return get("max");
	}

	public void setMaxRepeatCharacter(java.lang.Integer maxRepeatCharacter) {
		set("max_repeat_character", maxRepeatCharacter);
	}

	public java.lang.Integer getMaxRepeatCharacter() {
		return get("max_repeat_character");
	}

	public void setEnableNonAlphanumeric(java.lang.Boolean enableNonAlphanumeric) {
		set("enable_non_alphanumeric", enableNonAlphanumeric);
	}

	public java.lang.Boolean getEnableNonAlphanumeric() {
		return get("enable_non_alphanumeric");
	}

	public void setMinNonAlphanumeric(java.lang.Integer minNonAlphanumeric) {
		set("min_non_alphanumeric", minNonAlphanumeric);
	}

	public java.lang.Integer getMinNonAlphanumeric() {
		return get("min_non_alphanumeric");
	}

	public void setEnableDigits(java.lang.Boolean enableDigits) {
		set("enable_digits", enableDigits);
	}

	public java.lang.Boolean getEnableDigits() {
		return get("enable_digits");
	}

	public void setMinDigits(java.lang.Integer minDigits) {
		set("minDigits", minDigits);
	}

	public java.lang.Integer getMinDigits() {
		return get("minDigits");
	}

	public void setEnableLowercase(java.lang.Boolean enableLowercase) {
		set("enable_lowercase", enableLowercase);
	}

	public java.lang.Boolean getEnableLowercase() {
		return get("enable_lowercase");
	}

	public void setMinLowercase(java.lang.Integer minLowercase) {
		set("min_lowercase", minLowercase);
	}

	public java.lang.Integer getMinLowercase() {
		return get("min_lowercase");
	}

	public void setEnableUppercase(java.lang.Boolean enableUppercase) {
		set("enable_uppercase", enableUppercase);
	}

	public java.lang.Boolean getEnableUppercase() {
		return get("enable_uppercase");
	}

	public void setMinUppercase(java.lang.Integer minUppercase) {
		set("min_uppercase", minUppercase);
	}

	public java.lang.Integer getMinUppercase() {
		return get("min_uppercase");
	}

	public void setRetryOpen(java.lang.Boolean retryOpen) {
		set("retry_open", retryOpen);
	}

	public java.lang.Boolean getRetryOpen() {
		return get("retry_open");
	}

	public void setRequireVerifyCode(java.lang.Boolean requireVerifyCode) {
		set("require_verify_code", requireVerifyCode);
	}

	public java.lang.Boolean getRequireVerifyCode() {
		return get("require_verify_code");
	}

	public void setRetryNum(java.lang.Integer retryNum) {
		set("retry_num", retryNum);
	}

	public java.lang.Integer getRetryNum() {
		return get("retry_num");
	}

	public void setLockTime(java.lang.Integer lockTime) {
		set("lockTime", lockTime);
	}

	public java.lang.Integer getLockTime() {
		return get("lockTime");
	}

	public void setVerifyCodeNum(java.lang.Integer verifyCodeNum) {
		set("verify_code_num", verifyCodeNum);
	}

	public java.lang.Integer getVerifyCodeNum() {
		return get("verify_code_num");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
